---
title: Ipswich Massage And Herbal Spa
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: enquiry@ipswichmassage.com.au
description: Ipswich Massage and Herbal Spa is a natural therapy studio based in Ipswich
  Queensland which offers therapeutic treatments for your health, wellbeing and beauty
baseurl: 
url: 
facebook-link: https://www.facebook.com/ipswichmassage/
twitter_link: 
instagram-link: https://www.instagram.com/ipswichmassagecentre/
phone: 07 3281 6007
phone_nospaces: '0732816007'
address: 196 Brisbane Street, Ipswich
markdown: kramdown
plugins:
- jekyll-pug
- jekyll-feed
- jekyll-assets
assets:
  compression: true
