
title: COLOMBIAN COFFEE DEALER
email: colombiancoffeedealer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Colombian Coffee Dealer is a food and coffee and Burger Restaurant and Coffee stand in Brisbane Queensland, who produce and make authentic colombian coffee and cuisine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_link: https://www.facebook.com/colombiancoffeedealer/
twitter_link:
instagram_link: https://www.instagram.com/colombiancoffeedealer/
phone: 0426 197 873
phone_nospaces: 0426197873
address: 288 Edward Street, Brisbane City, Queensland

# Build settings
markdown: kramdown
#theme: minima
plugins:
    - jekyll-pug
    - jekyll-feed
    - jekyll-assets

assets:
  compression: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
