
title: Ipswich Massage And Herbal Spa
email: enquiry@ipswichmassage.com.au
description: >- # this means to ignore newlines until "baseurl:"
  Ipswich Massage and Herbal Spa is a natural therapy studio based in Ipswich Queensland which offers therapeutic treatments for your health, wellbeing and beauty
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_link:
twitter_link:
instagram_link:
phone: 0412 345 678
phone_nospaces: 0426197873
address:

# Build settings
markdown: kramdown
#theme: minima
plugins:
    - jekyll-pug
    - jekyll-feed
    - jekyll-assets

assets:
  compression: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

navigation:
- name: Home
  url: /
- name: About Us
  url: /about/
- name: Schedule
  url: /therapy-and-classes-schedule/
- name: Therapies
  dropdown: true
  items:
  - name: 'Osteopathy'
    url: '/osteopathy-therapy-information/'
- name: Blog
  url: /ipswich-massage-herbal-spa-blog/
- name: Shop
  url: /
- name: Gift Vouchers
  url: /
- name: Our App
  url: /
- name: Package Specials
  url: /
- name: Contact Us
  url: /contact/
