---
title: Ipswich Massage And Herbal Spa
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: enquiry@ipswichmassage.com.au
description: Ipswich Massage and Herbal Spa is a natural therapy studio based in Ipswich
  Queensland which offers therapeutic treatments for your health, wellbeing and beauty
baseurl: ''
url: ''
facebook_link: https://www.facebook.com/ipswichmassage/
twitter_link: 
instagram_link: https://www.instagram.com/ipswichmassagecentre/
<<<<<<< HEAD
phone: 07 3281 6007
phone_nospaces: 0732816007
=======
phone: 0412 345 678
phone_nospaces: '0426197873'
>>>>>>> 3f35fa013a417ee009588b9fac8cdb9beed22e4d
address: 196 Brisbane Street, Ipswich
markdown: kramdown
plugins:
- jekyll-pug
- jekyll-feed
- jekyll-assets
assets:
  compression: true
